# Generated by Django 5.1.6 on 2025-02-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_rename_sellers_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sellers',
            new_name='seller',
        ),
    ]
