# Generated by Django 5.1.6 on 2025-02-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_rename_sellers_products_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
